window.TheEraAgency = {
    models: [
        {
            pageName: 'ashley-harrell',
            modelName: 'Ashley H',
            profilesThumbnail: 'images/AshleyHarrellProfile.jpg',
            height: '5’6’’',
            weight: '110',
            shoe: '7',
            dress: '2',
            bust: '32C',
            waist: '24',
            hips: '33',
            hair: 'Dirty Blonde',
            eyes: 'Blue',
            instagram: 'smashharrell'
        },
        {
            pageName: 'autumn-allenbach',
            modelName: 'Autumn A',
            profilesThumbnail: 'images/AutumnAllenbachProfile.jpg',
            height: '5’9’’',
            weight: '110',
            shoe: '8.5',
            dress: '0-2',
            bust: '32C',
            waist: '24',
            hips: '34',
            hair: 'Dirty Blonde',
            eyes: 'Green',
            instagram: 'autumnallenbach'
        },
        {
            pageName: 'bailee-beachy',
            modelName: 'Bailee B',
            profilesThumbnail: 'images/BaileeBeachyProfile.jpg',
            height: '5’8’’',
            weight: '120',
            shoe: '8',
            dress: '2',
            bust: '32C',
            waist: '24',
            hips: '34',
            hair: 'Light Brown',
            eyes: 'Brown',
            instagram: 'baybeachy'
        },
        {
            pageName: 'bailey-hall',
            modelName: 'Bailey H',
            profilesThumbnail: 'images/BaileyHallProfile.jpg',
            height: '5’9’’',
            weight: '130',
            shoe: '9',
            dress: '4',
            bust: '34B',
            waist: '25',
            hips: '35',
            hair: 'Blonde',
            eyes: 'Green',
            instagram: 'bailey_raeeee'
        },
        {
            pageName: 'cathy-mccarthy',
            modelName: 'Cathy M',
            profilesThumbnail: 'images/CathyMcCarthyProfile.jpg',
            height: '5’6’’',
            weight: '118',
            shoe: '6',
            dress: '0',
            bust: '32B',
            waist: '25',
            hips: '34',
            hair: 'Dirty Blonde',
            eyes: 'Hazel',
            instagram: 'cathymccarthy'
        },
        {
            pageName: 'chelse-k',
            modelName: 'Chelse K',
            profilesThumbnail: 'images/ChelseKProfile.jpg',
            height: '5’10.5’’',
            weight: '122',
            shoe: '9.5',
            dress: '2',
            bust: '34C',
            waist: '25',
            hips: '34',
            hair: 'Blonde(short)',
            eyes: 'Green',
            instagram: 'dba_chelsek'
        },
        {
            pageName: 'dani-henricksen',
            modelName: 'Dani H',
            profilesThumbnail: 'images/DaniHenricksenProfile.jpg',
            height: '5’10’’',
            weight: '130',
            shoe: '8',
            dress: '4',
            bust: '34C',
            waist: '25',
            hips: '35',
            hair: 'Brown',
            eyes: 'Brown',
            instagram: 'danilove888'
        },
        {
            pageName: 'dani-mathers',
            modelName: 'Dani M',
            profilesThumbnail: 'images/DaniMathersProfile.jpg',
            height: '5’3’’(shoot much taller/print)',
            weight: '98',
            shoe: '6',
            dress: '00',
            bust: '33D',
            waist: '23',
            hips: '31',
            hair: 'Blonde (long)',
            eyes: 'Brown',
            instagram: 'missdanimathers'
        },
        {
            pageName: 'danielle-souza',
            modelName: 'Danielle S',
            profilesThumbnail: 'images/DanielleSouzaProfile.jpg',
            height: '5’9’’',
            weight: '120',
            shoe: '7',
            dress: '2',
            bust: '32B',
            waist: '24',
            hips: '34',
            hair: 'Brown',
            eyes: 'Brown',
            instagram: 'daniellensouza'
        },
        {
            pageName: 'emily-roche',
            modelName: 'Emily R',
            profilesThumbnail: 'images/EmilyRocheProfile.jpg',
            height: '5’6’’',
            weight: '110',
            shoe: '7',
            dress: '0',
            bust: '32C',
            waist: '23',
            hips: '32',
            hair: 'Blonde',
            eyes: 'Blue',
            instagram: 'emilyruthroche'
        },
        {
            pageName: 'holly-heitmann',
            modelName: 'Holly H',
            profilesThumbnail: 'images/HollyHeitmannProfile.jpg',
            height: '5’8’’',
            weight: '125',
            shoe: '8',
            dress: '2',
            bust: '34C',
            waist: '25',
            hips: '34',
            hair: 'Dark Brown',
            eyes: 'Brown',
            instagram: 'hollyhollyhollly'
        },
        {
            pageName: 'izzy-poulin',
            modelName: 'Izzy P',
            profilesThumbnail: 'images/IzzyPoulinProfile.jpg',
            height: '5’7’’',
            weight: '115',
            shoe: '7',
            dress: '2',
            bust: '34C',
            waist: '24',
            hips: '34',
            hair: 'Brown',
            eyes: 'Brown',
            instagram: 'izzyisup'
        },
        {
            pageName: 'jade-hataway',
            modelName: 'Jade H',
            profilesThumbnail: 'images/JadeHatawayProfile.jpg',
            height: '5’9’’',
            weight: '110',
            shoe: '9',
            dress: '0',
            bust: '32B',
            waist: '23',
            hips: '33',
            hair: 'Blonde',
            eyes: 'Blue',
            instagram: 'jadehataway'
        },
        {
            pageName: 'jena-sims',
            modelName: 'Jena S',
            profilesThumbnail: 'images/JenaSimsProfile.jpg',
            height: '5’8’’',
            weight: 'n/a',
            shoe: 'n/a',
            dress: 'n/a',
            bust: 'n/a',
            waist: 'n/a',
            hips: 'n/a',
            hair: 'Blonde',
            eyes: 'Brown',
            instagram: 'jenamsims'
        },
        {
            pageName: 'kandace-schipper',
            modelName: 'Kandace S',
            profilesThumbnail: 'images/KandaceSchipperProfile.jpg',
            height: '5’10.5’’',
            weight: '130',
            shoe: '10',
            dress: '2/4',
            bust: '34C',
            waist: '26',
            hips: '35',
            hair: 'Strawberry Blonde',
            eyes: 'Blue',
            instagram: 'kandyxo'
        },
        {
            pageName: 'karina-velez',
            modelName: 'Karina V',
            profilesThumbnail: 'images/KarinaVelezProfile.jpg',
            height: '5’7’’',
            weight: '102',
            shoe: '8',
            dress: '0',
            bust: '32C',
            waist: '23',
            hips: '34',
            hair: 'Auburn',
            eyes: 'Hazel',
            instagram: 'kayveee'
        },
        {
            pageName: 'kate-haveness',
            modelName: 'Kate H',
            profilesThumbnail: 'images/KateHavenessProfile.jpg',
            height: '5’10’’',
            weight: '125',
            shoe: '9',
            dress: '2/4',
            bust: '34',
            waist: '25',
            hips: '35',
            hair: 'Blonde',
            eyes: 'Green',
            instagram: 'kate_havness'
        },
        {
            pageName: 'kaylee-ricciardi',
            modelName: 'Kaylee R',
            profilesThumbnail: 'images/KayleeRicciardiProfile.jpg',
            height: '5’9’’',
            weight: '110',
            shoe: '8',
            dress: '2',
            bust: '32B',
            waist: '23',
            hips: '34',
            hair: 'Brown',
            eyes: 'Brown',
            instagram: 'kayleericciardi'
        },
        {
            pageName: 'kelsey-sliwinski',
            modelName: 'Kelsey S',
            profilesThumbnail: 'images/KelseySliwinskiProfile.jpg',
            height: '5’11’’',
            weight: '128',
            shoe: '10.5',
            dress: '3',
            bust: '34C',
            waist: '24',
            hips: '36',
            hair: 'Brown',
            eyes: 'Blue',
            instagram: 'kelseysliwinski'
        },
        {
            pageName: 'kendall-mathers',
            modelName: 'Kendall M',
            profilesThumbnail: 'images/KendallMathersProfile.jpg',
            height: '5’9’’',
            weight: '110',
            shoe: '9',
            dress: '0',
            bust: '32A',
            waist: '24',
            hips: '33',
            hair: 'Blonde',
            eyes: 'Blue',
            instagram: 'kendallrainmusic'
        },
        {
            pageName: 'lauren-s',
            modelName: 'Lauren S',
            profilesThumbnail: 'images/LaurenSProfile.jpg',
            height: '5’9’’',
            weight: '125',
            shoe: '8',
            dress: '2',
            bust: '32B',
            waist: '25',
            hips: '34',
            hair: 'Blonde',
            eyes: 'Blue',
            instagram: 'laurensmolka'
        },
        {
            pageName: 'liz-mule',
            modelName: 'Liz M',
            profilesThumbnail: 'images/LizMuleProfile.jpg',
            height: '5’7’’',
            weight: '110',
            shoe: '6',
            dress: '0',
            bust: '32C',
            waist: '24',
            hips: '34',
            hair: 'Brown',
            eyes: 'Light Brown',
            instagram: 'theslizzard'
        },
        {
            pageName: 'melissa-lebak',
            modelName: 'Melissa L',
            profilesThumbnail: 'images/MelissaLebakProfile.jpg',
            height: '5’6.5’’',
            weight: '118',
            shoe: '8',
            dress: '0',
            bust: '34A',
            waist: '24',
            hips: '34',
            hair: 'Brown',
            eyes: 'Green/Hazel',
            instagram: 'misslabak'
        },
        {
            pageName: 'natalie-paladin',
            modelName: 'Natalie P',
            profilesThumbnail: 'images/NataliePaladinProfile.jpg',
            height: '5’8’’',
            weight: '120',
            shoe: '7',
            dress: '2',
            bust: '34C',
            waist: '25',
            hips: '34',
            hair: 'Blonde',
            eyes: 'Blue',
            instagram: 'nataliekpaladiin'
        },
        {
            pageName: 'olivia-paladin',
            modelName: 'Olivia P',
            profilesThumbnail: 'images/OliviaPaladinProfile.jpg',
            height: '5’9’’',
            weight: '117',
            shoe: '7',
            dress: '0',
            bust: '32C',
            waist: '24',
            hips: '33',
            hair: 'Blonde',
            eyes: 'Brown',
            instagram: 'oliviapaladin'
        },
        {
            pageName: 'riley-richardson',
            modelName: 'Riley Richardson',
            profilesThumbnail: 'images/RileyRichardson6.jpg',
            height: '5’7’’',
            weight: '120',
            shoe: '8',
            dress: '2/4',
            bust: '34C',
            waist: '25',
            hips: '34',
            hair: 'Brown',
            eyes: 'Blue',
            instagram: 'thelifeof_ry'
        },
        {
            pageName: 'sam-prescott',
            modelName: 'Sam P',
            profilesThumbnail: 'images/SamPrescottProfile.jpg',
            height: '5’7’’',
            weight: 'n/a',
            shoe: 'n/a',
            dress: 'n/a',
            bust: 'n/a',
            waist: 'n/a',
            hips: 'n/a',
            hair: 'Light Brown',
            eyes: 'Brown',
            instagram: 'sammprescott'
        },
        {
            pageName: 'samantha-kimberlin',
            modelName: 'Samantha K',
            profilesThumbnail: 'images/SamanthaKimberlinProfile.jpg',
            height: '5’8’’',
            weight: '115',
            shoe: '9',
            dress: '2',
            bust: '34C',
            waist: '25',
            hips: '35',
            hair: 'Blonde',
            eyes: 'Brown',
            instagram: 'sammykayyyy'
        },
        {
            pageName: 'sydney-maler',
            modelName: 'Sydney M',
            profilesThumbnail: 'images/SydneyMalerProfile.jpg',
            height: '5’7.5’’',
            weight: '130',
            shoe: '9',
            dress: '4',
            bust: '36D',
            waist: '24',
            hips: '36',
            hair: 'Dirty Blonde',
            eyes: 'Hazel',
            instagram: 'sydney.a.maler'
        },
        {
            pageName: 'talia-williamson',
            modelName: 'Talia W',
            profilesThumbnail: 'images/TaliaWilliamsonProfile.jpg',
            height: '5’11’’',
            weight: '130',
            shoe: '9.5',
            dress: '2',
            bust: '32C',
            waist: '26',
            hips: '36',
            hair: 'Dark Brown',
            eyes: 'Brown',
            instagram: 'taliawilliamson'
        }
    ]
}
